/**
 * [TEST]Voice Agent API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class AttachmentPublic {
    'relatedObjectType'?: string | null;
    'relatedObjectSubtype'?: string | null;
    'relatedObjectId'?: number | null;
    'filename'?: string;
    'objectKey'?: string;
    'contentType'?: string;
    'id': number;
    'downloadUrl'?: string | null;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "relatedObjectType",
            "baseName": "related_object_type",
            "type": "string",
            "format": ""
        },
        {
            "name": "relatedObjectSubtype",
            "baseName": "related_object_subtype",
            "type": "string",
            "format": ""
        },
        {
            "name": "relatedObjectId",
            "baseName": "related_object_id",
            "type": "number",
            "format": ""
        },
        {
            "name": "filename",
            "baseName": "filename",
            "type": "string",
            "format": ""
        },
        {
            "name": "objectKey",
            "baseName": "object_key",
            "type": "string",
            "format": ""
        },
        {
            "name": "contentType",
            "baseName": "content_type",
            "type": "string",
            "format": ""
        },
        {
            "name": "id",
            "baseName": "id",
            "type": "number",
            "format": ""
        },
        {
            "name": "downloadUrl",
            "baseName": "download_url",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return AttachmentPublic.attributeTypeMap;
    }

    public constructor() {
    }
}
