/**
 * [TEST]Voice Agent API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class MyPlan {
    'id': number;
    'name': string;
    'interval': string;
    'tier': string;
    'expiredAt': Date;
    'isExpired'?: boolean | null;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "number",
            "format": ""
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "string",
            "format": ""
        },
        {
            "name": "interval",
            "baseName": "interval",
            "type": "string",
            "format": ""
        },
        {
            "name": "tier",
            "baseName": "tier",
            "type": "string",
            "format": ""
        },
        {
            "name": "expiredAt",
            "baseName": "expired_at",
            "type": "Date",
            "format": "date-time"
        },
        {
            "name": "isExpired",
            "baseName": "is_expired",
            "type": "boolean",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return MyPlan.attributeTypeMap;
    }

    public constructor() {
    }
}
