/**
 * [TEST]Voice Agent API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class OrderDetail {
    'id': number;
    'planId': number;
    'planName': string;
    'amount': number;
    'interval': string;
    'expiredAt': Date;
    'points': number;
    'currency': string;
    'paidAt': Date | null;
    'paidEmail': string | null;
    'paidDetail': string | null;
    'status': string;
    'createdById': number;
    'createdByName': string;
    'createdAt': Date | null;
    'updatedAt': Date | null;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "number",
            "format": ""
        },
        {
            "name": "planId",
            "baseName": "plan_id",
            "type": "number",
            "format": ""
        },
        {
            "name": "planName",
            "baseName": "plan_name",
            "type": "string",
            "format": ""
        },
        {
            "name": "amount",
            "baseName": "amount",
            "type": "number",
            "format": ""
        },
        {
            "name": "interval",
            "baseName": "interval",
            "type": "string",
            "format": ""
        },
        {
            "name": "expiredAt",
            "baseName": "expired_at",
            "type": "Date",
            "format": "date-time"
        },
        {
            "name": "points",
            "baseName": "points",
            "type": "number",
            "format": ""
        },
        {
            "name": "currency",
            "baseName": "currency",
            "type": "string",
            "format": ""
        },
        {
            "name": "paidAt",
            "baseName": "paid_at",
            "type": "Date",
            "format": "date-time"
        },
        {
            "name": "paidEmail",
            "baseName": "paid_email",
            "type": "string",
            "format": ""
        },
        {
            "name": "paidDetail",
            "baseName": "paid_detail",
            "type": "string",
            "format": ""
        },
        {
            "name": "status",
            "baseName": "status",
            "type": "string",
            "format": ""
        },
        {
            "name": "createdById",
            "baseName": "created_by_id",
            "type": "number",
            "format": ""
        },
        {
            "name": "createdByName",
            "baseName": "created_by_name",
            "type": "string",
            "format": ""
        },
        {
            "name": "createdAt",
            "baseName": "created_at",
            "type": "Date",
            "format": "date-time"
        },
        {
            "name": "updatedAt",
            "baseName": "updated_at",
            "type": "Date",
            "format": "date-time"
        }    ];

    static getAttributeTypeMap() {
        return OrderDetail.attributeTypeMap;
    }

    public constructor() {
    }
}
