/**
 * [TEST]Voice Agent API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class PointsLogPublic {
    'id'?: number;
    'relatedObjectType'?: string | null;
    'relatedObjectId'?: number | null;
    'points'?: number;
    'remainingPoints'?: number;
    'action'?: string;
    'description'?: string | null;
    'userId'?: number;
    'operatorName'?: string;
    'createdAt'?: Date | null;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "number",
            "format": ""
        },
        {
            "name": "relatedObjectType",
            "baseName": "related_object_type",
            "type": "string",
            "format": ""
        },
        {
            "name": "relatedObjectId",
            "baseName": "related_object_id",
            "type": "number",
            "format": ""
        },
        {
            "name": "points",
            "baseName": "points",
            "type": "number",
            "format": ""
        },
        {
            "name": "remainingPoints",
            "baseName": "remaining_points",
            "type": "number",
            "format": ""
        },
        {
            "name": "action",
            "baseName": "action",
            "type": "string",
            "format": ""
        },
        {
            "name": "description",
            "baseName": "description",
            "type": "string",
            "format": ""
        },
        {
            "name": "userId",
            "baseName": "user_id",
            "type": "number",
            "format": ""
        },
        {
            "name": "operatorName",
            "baseName": "operator_name",
            "type": "string",
            "format": ""
        },
        {
            "name": "createdAt",
            "baseName": "created_at",
            "type": "Date",
            "format": "date-time"
        }    ];

    static getAttributeTypeMap() {
        return PointsLogPublic.attributeTypeMap;
    }

    public constructor() {
    }
}
