/**
 * [TEST]Voice Agent API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class PresignedUrlCreate {
    'filename': string;
    'relatedObjectType': string | null;
    'relatedObjectSubtype': string | null;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "filename",
            "baseName": "filename",
            "type": "string",
            "format": ""
        },
        {
            "name": "relatedObjectType",
            "baseName": "related_object_type",
            "type": "string",
            "format": ""
        },
        {
            "name": "relatedObjectSubtype",
            "baseName": "related_object_subtype",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return PresignedUrlCreate.attributeTypeMap;
    }

    public constructor() {
    }
}
