/**
 * [TEST]Voice Agent API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { CompanyPublic } from '../models/CompanyPublic';
import { RolePublic } from '../models/RolePublic';
import { HttpFile } from '../http/http';

export class UserPublic {
    'username': string;
    'cellPhone'?: string | null;
    'fullName': string;
    'email': string;
    'companyId'?: number | null;
    'id': number;
    'roles'?: Array<RolePublic> | null;
    'company'?: CompanyPublic | null;
    'planId'?: number | null;
    'usedPoints': number;
    'remainingPoints': number;
    'mainId': number | null;
    'isSuperuser': boolean;
    'isMain': boolean;
    'isActive': boolean;
    'isVerified': boolean;
    'isDeleted': boolean;
    'createdById': number | null;
    'createdByName': string | null;
    'createdAt': Date | null;
    'updatedAt': Date | null;
    'roleName'?: string;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "username",
            "baseName": "username",
            "type": "string",
            "format": ""
        },
        {
            "name": "cellPhone",
            "baseName": "cell_phone",
            "type": "string",
            "format": ""
        },
        {
            "name": "fullName",
            "baseName": "full_name",
            "type": "string",
            "format": ""
        },
        {
            "name": "email",
            "baseName": "email",
            "type": "string",
            "format": ""
        },
        {
            "name": "companyId",
            "baseName": "company_id",
            "type": "number",
            "format": ""
        },
        {
            "name": "id",
            "baseName": "id",
            "type": "number",
            "format": ""
        },
        {
            "name": "roles",
            "baseName": "roles",
            "type": "Array<RolePublic>",
            "format": ""
        },
        {
            "name": "company",
            "baseName": "company",
            "type": "CompanyPublic",
            "format": ""
        },
        {
            "name": "planId",
            "baseName": "plan_id",
            "type": "number",
            "format": ""
        },
        {
            "name": "usedPoints",
            "baseName": "used_points",
            "type": "number",
            "format": ""
        },
        {
            "name": "remainingPoints",
            "baseName": "remaining_points",
            "type": "number",
            "format": ""
        },
        {
            "name": "mainId",
            "baseName": "main_id",
            "type": "number",
            "format": ""
        },
        {
            "name": "isSuperuser",
            "baseName": "is_superuser",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "isMain",
            "baseName": "is_main",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "isActive",
            "baseName": "is_active",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "isVerified",
            "baseName": "is_verified",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "isDeleted",
            "baseName": "is_deleted",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "createdById",
            "baseName": "created_by_id",
            "type": "number",
            "format": ""
        },
        {
            "name": "createdByName",
            "baseName": "created_by_name",
            "type": "string",
            "format": ""
        },
        {
            "name": "createdAt",
            "baseName": "created_at",
            "type": "Date",
            "format": "date-time"
        },
        {
            "name": "updatedAt",
            "baseName": "updated_at",
            "type": "Date",
            "format": "date-time"
        },
        {
            "name": "roleName",
            "baseName": "role_name",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return UserPublic.attributeTypeMap;
    }

    public constructor() {
    }
}
